baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pulse Docs'
theme = 'hugo-book'

[markup.goldmark.renderer]
    unsafe = true

[params]
    BookTheme = 'light'
    BookSection = '/'
    BookSearch = false
    BookToC = false